# Generated by Django 4.0.6 on 2024-02-18 16:04

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50, verbose_name='分类名称')),
                ('href', models.CharField(default='', max_length=100, verbose_name='分类路径')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('img', models.CharField(max_length=100, verbose_name='路径')),
            ],
            options={
                'verbose_name': '聚焦',
                'verbose_name_plural': '聚焦',
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=20, verbose_name='友链站点名称')),
                ('path', models.CharField(max_length=100, verbose_name='地址路径')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='站点名称')),
                ('avatar', models.CharField(max_length=200, verbose_name='站点图标')),
                ('slogan', models.CharField(max_length=200, verbose_name='站点标语')),
                ('domain', models.CharField(max_length=200, verbose_name='站点域名')),
                ('notice', models.CharField(max_length=200, verbose_name='站点备注')),
                ('desc', models.CharField(max_length=200, verbose_name='站点描述')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('icon', models.CharField(max_length=200, verbose_name='图标')),
                ('color', models.CharField(max_length=20, verbose_name='颜色')),
                ('href', models.CharField(max_length=100, verbose_name='路径')),
            ],
            options={
                'verbose_name': '社交信息',
                'verbose_name_plural': '社交信息',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=20, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='文章标题')),
                ('isTop', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('isHot', models.BooleanField(default=False, verbose_name='是否热门')),
                ('isShow', models.BooleanField(default=False, verbose_name='是否显示')),
                ('banner', models.CharField(default='', max_length=200, verbose_name='文章图标')),
                ('summary', models.TextField(default='', max_length=500, verbose_name='内容摘要')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('viewsCount', models.IntegerField(default=0, verbose_name='查看数')),
                ('commentsCount', models.IntegerField(default=0, verbose_name='评论数')),
                ('blogSource', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='文章来源')),
                ('pubTime', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.blogcategory', verbose_name='文章分类')),
                ('tags', models.ManyToManyField(blank=True, default=None, related_name='tag_post', to='blog.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
            },
        ),
    ]
